@versions(Auto)
@context(PREV,infinity):-
  (((^)|(\.)+)(\s*\\n)*)\s*.
@glue:-.
@global_unique(MAIN,infinity):-
   (([^\w\.]+(\w+)->{P0}[^\.]*\.)->{Grammar.ru{SENTENCE}}(*PRUNE))?=>{
      xpathf(SENTENCE,'MVv1ii','иметь','значение','true')
   }.
 @auto:-MAIN:"//P0/text()" => "Name","Positive" => "Restrict",randomid() => "ID".
 @goal:-xpath('MAIN','//P0/text()',[VNameText0]),assertz(e_svar_restrict(VNameText0,'Positive','randomid')),!.
 @done:-clear_db.

