@versions(Auto)
@context(PREV,infinity):-
  (((^)|(\.)+)(\s*\\n)*)\s*.
@glue:-.
@global_unique(MAIN,infinity):-
   (([^\x22\x27\.]+[\x22\x27]([^\x22\x27]+)->{P0}[\x22\x27][^\.]*\.)->{Grammar.ru{SENTENCE}}(*PRUNE))?=>{
      xpathf(SENTENCE,'MVv1ii','Добавим','функции','true')
   }.
 @auto:-MAIN:"//P0/text()" => "Funs","ID238" => "ID".
 @goal:-xpath('MAIN','//P0/text()',[VFunsText0]),assertz(e_ssolver_fs(VFunsText0,'ID238')),!.
 @done:-clear_db.

