@versions(Auto)
@context(PREV,infinity):-
  (((^)|(\.)+)(\s*\\n)*)\s*.
@glue:-.
@global_unique(MAIN,1):-
   (([^\w\.]+(\w+)->{P0}[^\w\.]+(\w+)->{P1}[^\.]*\.)->{Grammar.ru{SENTENCE}}(*PRUNE))?=>{
      xpathf(SENTENCE,'MVv1ii','зададим','модификатор','true')
   }.
 @auto:-MAIN:"//P0/text()" => "Var","ID204" => "ID".
 @goal:-xpath('MAIN','//P0/text()',[VVarText1]),assertz(e_smodification(VVarText1,'ID204')),!.
 @done:-clear_db.
